[variables]
NIXPACKS_PYTHON_VERSION = "3.12"

[phases.setup]
nixPkgs = ["dejavu_fonts", "noto-fonts"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "python main.py"
# deployed: 1775848416
