name: Deploy to Cloudflare Pages

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install & Build
        run: |
          cd frontend
          npm install
          npm run build

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: mr0Wxl306cD3SezN0DBimHG0w9JlgAzsbxqcyeoV
          accountId: 42c8b5c5e608bab52771ec762edd61ff
          command: pages deploy frontend/out --project-name=caucashub --branch=master
